version: '3.1'

services:
  app:
    image: localhost/warn-reporter:dev
    build:
      context: .
    volumes:
      - ./build:/build
      - .:/code
    ports: [127.0.0.1:8000:8000]
    environment:
      UVICORN_RELOAD: 'true'
