from __future__ import annotations

import glob
import re
from pathlib import Path

import alembic.command
from alembic.config import Config
from alembic.util import AutogenerateDiffsDetected

from .. import orm, settings
from ..utils import BaseCommand, FuncCommand


class AutoHelper:

    def __init__(self, message: str|None = None):
        self.message = message

    def run(self) -> None:
        self.config = Config(settings.ALEMBIC_INI)
        with orm.engine.begin() as connection:
            self.config.attributes['connection'] = connection
            if self.has_changes():
                self.generate()

    def has_changes(self) -> bool:
        try:
            alembic.command.check(self.config)
        except AutogenerateDiffsDetected:
            return True
        return False

    def generate(self) -> None:
        rev_id, parent = self.get_rev()
        alembic.command.revision(
            config=self.config,
            message=self.message,
            autogenerate=True,
            rev_id=rev_id,
            depends_on=parent)

    def get_rev(self) -> tuple[str, str|None]:
        revdir = Path(__file__).parent/'versions'
        files = sorted(
            filter(
                lambda x: re.match(r'^\d{4}', x.name),
                map(Path, glob.glob(f'{revdir}/*.py'))),
            reverse=True)
        if files:
            parent = files[0].name[:4]
            rev_id = str(int(parent) + 1).zfill(4)
        else:
            parent = None
            rev_id = '0001'
        return rev_id, parent

def migrate() -> None:
    'Run schema migrations'
    config = Config(settings.ALEMBIC_INI)
    with orm.engine.begin() as connection:
        config.attributes['connection'] = connection
        alembic.command.upgrade(config, 'head')
    orm.load_naics()

def auto(message: str|None = None) -> None:
    'Auto-generate schema migration'
    AutoHelper(message).run()

class MigrateCommand(FuncCommand(migrate)):
    pass

class AutoCommand(FuncCommand(auto)):

    @classmethod
    def add_arguments(cls, parser):
        parser.add_argument('--message', '-m', default='auto', help='Migration message, default auto')


class AlembicCommand(BaseCommand):

    from alembic.config import CommandLine

    @classmethod
    def init_parser(cls, parser):
        for action in cls.CommandLine().parser._actions:
            if action.dest in ('help', 'config'):
                continue
            parser._add_action(action)

    def setup(self, opts):
        if not hasattr(opts, 'cmd'):
            self.parser.error('too few arguments')
        self.config = Config(settings.ALEMBIC_INI, ini_section=opts.name, cmd_opts=opts)

    def run(self):
        self.CommandLine().run_cmd(self.config, self.opts)

class Command(BaseCommand):
    'Migration commands'
    commands = dict(migrate=MigrateCommand, auto=AutoCommand, alembic=AlembicCommand)
