from __future__ import annotations

import glob
import re
from pathlib import Path

import alembic.command
from alembic.config import Config
from alembic.util import AutogenerateDiffsDetected

from .. import settings
from ..orm import engine
from ..utils import BaseCommand


class Command(BaseCommand):
    'Auto-generate alembic revision'

    @classmethod
    def add_arguments(cls, parser) -> None:
        parser.add_argument('--message', '-m', default='auto')

    def run(self):
        self.config = Config(settings.ALEMBIC_INI)
        with engine.begin() as connection:
            self.config.attributes['connection'] = connection
            if self.has_changes():
                self.generate()

    def has_changes(self) -> bool:
        try:
            alembic.command.check(self.config)
        except AutogenerateDiffsDetected:
            return True
        return False

    def generate(self) -> None:
        rev_id, parent = self.get_rev()
        alembic.command.revision(
            config=self.config,
            message=self.opts.message,
            autogenerate=True,
            rev_id=rev_id,
            depends_on=parent)

    def get_rev(self) -> tuple[str, str|None]:
        revdir = Path(__file__).parent/'versions'
        files = sorted(
            filter(
                lambda x: re.match(r'^\d{4}', x.name),
                map(Path, glob.glob(f'{revdir}/*.py'))),
            reverse=True)
        if files:
            parent = files[0].name[:4]
            rev_id = str(int(parent) + 1).zfill(4)
        else:
            parent = None
            rev_id = '0001'
        return rev_id, parent

if __name__ == '__main__':
    Command.main()
