"""Initial

Revision ID: 164b111b7023
Revises: 
Create Date: 2024-05-24 09:39:51.828424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.create_table('artifact',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('path', sa.String(length=2083), nullable=False),
        sa.Column('url', sa.String(length=2083), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('mimetype', sa.String(length=255), nullable=False),
        sa.Column('size', sa.BigInteger(), nullable=False),
        sa.Column('sha1', sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('path'))
    op.create_table('naics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=32), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_naics_code'), 'naics', ['code'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_naics_title'), 'naics', ['title'], unique=False, if_not_exists=True)
    op.create_table('report',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('company', sa.String(length=512), nullable=False),
        sa.Column('company_norm', sa.String(length=512), nullable=False),
        sa.Column('reported', sa.DateTime(timezone=True), nullable=False),
        sa.Column('state', sa.String(length=2), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('starting', sa.DateTime(timezone=True), nullable=True),
        sa.Column('employees', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(length=64), nullable=True),
        sa.Column('url', sa.String(length=2083), nullable=True),
        sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_report_company'), 'report', ['company'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_report_company_norm'), 'report', ['company_norm'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_report_state'), 'report', ['state'], unique=False, if_not_exists=True)
    op.create_table('statestat',
        sa.Column('id', sa.String(length=2), nullable=False),
        sa.Column('last_reported', sa.DateTime(timezone=True), nullable=True),
        sa.Column('reports_count', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'))
    op.create_table('artifactreport',
        sa.Column('artifact_id', sa.Uuid(), nullable=False),
        sa.Column('report_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id']),
        sa.ForeignKeyConstraint(['report_id'], ['report.id']),
        sa.PrimaryKeyConstraint('artifact_id', 'report_id'))
    op.create_table('naicsreport',
        sa.Column('naics_id', sa.Integer(), nullable=False),
        sa.Column('report_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['naics_id'], ['naics.id']),
        sa.ForeignKeyConstraint(['report_id'], ['report.id']),
        sa.PrimaryKeyConstraint('naics_id', 'report_id'))
    op.create_table('company',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=512), nullable=False),
        sa.Column('name_norm', sa.String(length=512), nullable=False),
        sa.Column('name_canon', sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'))
    op.create_index(op.f('ix_company_name_canon'), 'company', ['name_canon'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_company_name_norm'), 'company', ['name_norm'], unique=False, if_not_exists=True)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('naicsreport')
    op.drop_table('artifactreport')
    op.drop_table('statestat')
    op.drop_index(op.f('ix_report_state'), table_name='report')
    op.drop_index(op.f('ix_report_company_norm'), table_name='report')
    op.drop_index(op.f('ix_report_company'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_naics_title'), table_name='naics')
    op.drop_index(op.f('ix_naics_code'), table_name='naics')
    op.drop_table('naics')
    op.drop_index(op.f('ix_company_name_norm'), table_name='company')
    op.drop_index(op.f('ix_company_name_canon'), table_name='company')
    op.drop_table('company')
    op.drop_table('artifact')
    # ### end Alembic commands ###
