"""cascade_m2m

Revision ID: 0003
Revises: 0002
Create Date: 2024-06-06 05:25:19.886821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = '0002'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artifactreport_report_id_fkey', 'artifactreport', type_='foreignkey')
    op.drop_constraint('artifactreport_artifact_id_fkey', 'artifactreport', type_='foreignkey')
    op.create_foreign_key(None, 'artifactreport', 'report', ['report_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'artifactreport', 'artifact', ['artifact_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('naicsreport_report_id_fkey', 'naicsreport', type_='foreignkey')
    op.drop_constraint('naicsreport_naics_id_fkey', 'naicsreport', type_='foreignkey')
    op.create_foreign_key(None, 'naicsreport', 'naics', ['naics_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'naicsreport', 'report', ['report_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'naicsreport', type_='foreignkey')
    op.drop_constraint(None, 'naicsreport', type_='foreignkey')
    op.create_foreign_key('naicsreport_naics_id_fkey', 'naicsreport', 'naics', ['naics_id'], ['id'])
    op.create_foreign_key('naicsreport_report_id_fkey', 'naicsreport', 'report', ['report_id'], ['id'])
    op.drop_constraint(None, 'artifactreport', type_='foreignkey')
    op.drop_constraint(None, 'artifactreport', type_='foreignkey')
    op.create_foreign_key('artifactreport_artifact_id_fkey', 'artifactreport', 'artifact', ['artifact_id'], ['id'])
    op.create_foreign_key('artifactreport_report_id_fkey', 'artifactreport', 'report', ['report_id'], ['id'])
    # ### end Alembic commands ###
