"""reportmod

Revision ID: 0004
Revises: 0003
Create Date: 2024-06-09 08:21:00.223648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = '0003'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportmod',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ns', sa.UUID(), nullable=False),
    sa.Column('first_scraped', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportmod_ns'), 'reportmod', ['ns'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reportmod_ns'), table_name='reportmod')
    op.drop_table('reportmod')
    # ### end Alembic commands ###
