"""naics_tree

Revision ID: 0005
Revises: 0004
Create Date: 2025-01-29 23:39:54.874056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy.orm import Session
    from wrep import settings
    import requests
    rep = requests.get(settings.NAICS_DOWNLOAD)
    rep.raise_for_status()
    entrymap = {entry['code']: entry for entry in rep.json()}
    op.add_column('naics', sa.Column('left', sa.Integer(), nullable=True))
    op.add_column('naics', sa.Column('right', sa.Integer(), nullable=True))
    op.add_column('naics', sa.Column('depth', sa.Integer(), nullable=True))
    op.add_column('naics', sa.Column('parent', sa.Integer(), nullable=True))
    from wrep.orm import Naics
    with Session(op.get_bind()) as session:
        for naics in session.scalars(sa.select(Naics)):
            entry = entrymap[naics.id]
            for name in ('left', 'right', 'depth', 'parent'):
                setattr(naics, name, entry[name])
            session.add(naics)
        session.commit()
    op.alter_column('naics', 'left', nullable=False)
    op.alter_column('naics', 'right', nullable=False)
    op.alter_column('naics', 'depth', nullable=False)
    op.create_unique_constraint('naics_right_key', 'naics', ['right'])
    op.create_unique_constraint('naics_left_key', 'naics', ['left'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('naics_left_key', 'naics')
    op.drop_constraint('naics_right_key', 'naics')
    op.drop_column('naics', 'parent')
    op.drop_column('naics', 'depth')
    op.drop_column('naics', 'right')
    op.drop_column('naics', 'left')
    # ### end Alembic commands ###
